use Card.IsNonAttribute
Fluorohydride/ygopro-scripts pull request #1997
Opened 2022-11-26 10:15 UTC by mercury233

simplify https://github.com/Fluorohydride/ygopro-scripts/commit/e84d99cb79476ce97e5d43966a7b62e996eda8d6
require https://github.com/Fluorohydride/ygopro-core/pull/483

2022-11-26 10:16 UTC, mercury233 commented
I think we should confirm about whether _Visas Starfrost_ can target _Light and Darkness Dragon_ to destroy.

2022-11-28 15:38 UTC, salix5 requested changes
このカード名の効果は１ターンに１度しか使用できない。
①：このカードが墓地に存在し、自分フィールドにモンスターが存在しない場合、手札から水属性モンスター１体を捨てて発動できる。このカードを特殊召喚する。この効果で特殊召喚したターンのバトルフェイズ開始時に、水属性モンスター以外の自分フィールドのモンスターを全て破壊する。 

> 水属性モンスター以外の自分フィールドのモンスターを全て破壊する
Keep: IsFaceup() and IsAttribute(ATTRIBUTE_WATER)
Destroy: IsFacedown() or not IsAttribute(ATTRIBUTE_WATER)

The original version is correct.

2022-11-28 23:52 UTC, mercury233 commented
@salix5 Fixed

2022-11-29 00:50 UTC, salix5 approved these changes

2022-11-30 01:27 UTC, merged

2022-12-05 02:55 UTC, mercury233 commented
@salix5 
> Q.
「妖精王 アルヴェルド」の『地属性以外のフィールド上の全てのモンスターの攻撃力・守備力は５００ポイントダウンする』効果を発動した場合、「精霊術師 ドリアード」の攻撃力・守備力をダウンしますか？
A.
「精霊術師 ドリアード」の攻撃力・守備力は500ダウンします。
 
> Q.
「フィッシュボーグ－アーチャー」の『この効果で特殊召喚したターンのバトルフェイズ開始時に、水属性モンスター以外の自分フィールドのモンスターを全て破壊する』処理によって、「精霊術師 ドリアード」を破壊されますか？
A.
「精霊術師 ドリアード」は破壊されます。
 
> Q.
「サイレントアビス」の『フィールド上に表側表示で存在する水属性モンスター以外のモンスターを全て破壊する』効果を発動した場合、「精霊術師 ドリアード」を破壊されますか？
A.
「精霊術師 ドリアード」は破壊されます。

> Q.
自分フィールドに「アイスバーン」と水属性モンスターである「精霊術師 ドリアード」が表側表示で存在し、「死者蘇生」の効果で2体目「精霊術師 ドリアード」が特殊召喚した場合、「アイスバーン」の『自分フィールド上に水属性モンスターが表側表示で存在し、水属性以外のモンスターが召喚・特殊召喚に成功した時、そのモンスターは守備表示になる』効果を発動しますか？
A.
「アイスバーン」の効果が発動します。
 
> Q.
自分フィールドに、アイスカウンターが3つ置かれている「スノーダスト・ジャイアント」と「精霊術師 ドリアード」が表側表示で存在する場合、「スノーダスト・ジャイアント」の効果によって「精霊術師 ドリアード」の攻撃力はダウンしますか？
A.
「精霊術師 ドリアード」の攻撃力は600ダウンします。
 
> Q.
自分のペンデュラムゾーンに、ヴェネミーカウンターが3つ置かれている「スターヴ・ヴェネミー・ドラゴン」が存在し、モンスターゾーンに「光と闇の竜」が表側表示で存在する場合、「スターヴ・ヴェネミー・ドラゴン」のペンデュラム効果によって「光と闇の竜」の攻撃力はダウンしますか？
A.
「光と闇の竜」の攻撃力は600ダウンします。

It seems that _「闇属性モンスター以外のモンスター」"_ are same as _「闇属性以外のモンスター」_

2022-12-05 05:39 UTC, salix5 commented
https://www.db.yugioh-card.com/yugiohdb/card_search.action?ope=2&cid=16428&request_locale=ja
 スターヴ・ヴェネミー・ドラゴン
 ペンデュラム効果 
②：ドラゴン族・闇属性モンスター以外のフィールドのモンスターの攻撃力はフィールドのヴェネミーカウンターの数×２００ダウンする。

Maybe the filter is:
```lua
not (c:GetRace()==RACE_DRAGON and c:GetAttribute()==ATTRIBUTE_DARK)
```